"""Step 02: audit participant/session/exercise coverage and check feasibility of the team design.

Team design ("everyone starts at the same time"): a team of N athletes records k sets per exercise
on their first recording day; the model is tested on later days of (a) those athletes and (b)
athletes who were never recorded. Needs participants with >= 2 recording days.

Reads outputs/tables/manifest.csv, writes outputs/tables/audit_*.csv and DATA_AUDIT.md.

    python steps/02_audit.py
"""
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

TABLES = ROOT / "outputs" / "tables"
README_TOTALS = dict(participants=35, sessions=158, bouts=2355, reps=23738, classes=15)
N_NEW = 6                                  # athletes held out as "never recorded" in each repeat
TEAM_SIZES = [2, 4, 6, 8, 12, 16]  # candidates; trimmed to the pool, and the pool maximum is appended


def dist(s):
    """Compact 'value: count' string for a small-integer distribution."""
    return ", ".join(f"{k}: {v}" for k, v in s.value_counts().sort_index().items())


def main():
    raw = pd.read_csv(TABLES / "manifest.csv", parse_dates=["session_date"])
    m = raw[raw.include].copy()

    # --- Totals vs README ---------------------------------------------------------------------
    totals = dict(participants=m.participant_id.nunique(), sessions=m.session_id.nunique(),
                  bouts=len(m), reps=int(m.rep_count.sum()), classes=m.exercise_class.nunique())

    # --- Per participant ----------------------------------------------------------------------
    pp = m.groupby("participant_id").agg(
        sessions=("session_id", "nunique"), days=("session_date", "nunique"), bouts=("session_id", "size"),
        classes=("exercise_class", "nunique"), reps=("rep_count", "sum"),
        experience_months=("experience_months", "first"), gender=("gender", "first"),
        median_fs=("estimated_sampling_rate", "median"),
    )
    day1 = m[m.day_order == 1]
    later = m[m.day_order > 1]
    d1 = day1.groupby(["participant_id", "exercise_class"]).size().unstack(fill_value=0).reindex(columns=range(15), fill_value=0)
    pp["day1_sessions"] = day1.groupby("participant_id").session_id.nunique()
    pp["day1_classes_ge1"] = (d1 >= 1).sum(axis=1)
    pp["day1_classes_ge2"] = (d1 >= 2).sum(axis=1)
    pp["later_bouts"] = later.groupby("participant_id").size().reindex(pp.index, fill_value=0)
    pp["later_classes"] = later.groupby("participant_id").exercise_class.nunique().reindex(pp.index, fill_value=0)
    # classes present on day 1 AND on a later day (recurrence across days)
    rec = {}
    for pid, g in m.groupby("participant_id"):
        a = set(g[g.day_order == 1].exercise_class)
        b = set(g[g.day_order > 1].exercise_class)
        rec[pid] = len(a & b)
    pp["classes_recurring_across_days"] = pd.Series(rec)
    pp["eligible"] = pp.days >= 2
    pp["eligible_k1"] = pp.eligible & (pp.day1_classes_ge1 == 15) & (pp.later_classes == 15)
    pp["eligible_k2"] = pp.eligible_k1 & (pp.day1_classes_ge2 == 15)

    # --- Per class ----------------------------------------------------------------------------
    pc = m.groupby(["exercise_class", "exercise_name"]).agg(
        bouts=("session_id", "size"), reps=("rep_count", "sum"), participants=("participant_id", "nunique"),
        median_bout_s=("duration_seconds", "median"),
    ).reset_index()
    per_sess_classes = m.groupby("session_id").exercise_class.nunique()

    # --- Sampling rate ------------------------------------------------------------------------
    fs = m.estimated_sampling_rate
    fs_pp = pp.median_fs

    TABLES.mkdir(parents=True, exist_ok=True)
    pp.to_csv(TABLES / "audit_participants.csv")
    pc.to_csv(TABLES / "audit_classes.csv", index=False)
    d1.to_csv(TABLES / "audit_day1_sets_per_class.csv")

    # --- Feasible grid ------------------------------------------------------------------------
    n_elig = int(pp.eligible_k1.sum())
    n_k2 = int(pp.eligible_k2.sum())
    # One pool for both k so that k=1 vs k=2 is paired (same teams, same test athletes)
    pp["in_pool"] = pp.eligible_k2
    pp.to_csv(TABLES / "audit_participants.csv")
    max_team = n_k2 - N_NEW
    teams = [n for n in TEAM_SIZES if n <= max_team]
    if teams and teams[-1] != max_team:
        teams.append(max_team)

    # --- Write DATA_AUDIT.md ------------------------------------------------------------------
    excl = raw[~raw.include].exclude_reason.value_counts()
    L = ["# DATA_AUDIT", "",
         "Generated by `python steps/02_audit.py` from `outputs/tables/manifest.csv` (built by `steps/01_manifest.py`).",
         "Dataset: `data/uLift-dataset` (JeiKeiLim/uLift-dataset @ 58edaf0). Only workout bouts are used (rest and whole-session files are ignored).",
         "", "## 1. Totals vs README", "",
         "| | README | Found (included) |", "|---|---|---|"]
    for k, v in README_TOTALS.items():
        L.append(f"| {k} | {v:,} | {totals[k]:,} |")
    L += ["", f"- Raw workout bouts in the files: {len(raw):,}. Excluded: "
          + "; ".join(f"{v} × {k}" for k, v in excl.items()) + ".",
          "- The README totals match only after excluding those bouts; the authors' loader drops them for the same reason.",
          f"- Files that could not be parsed or failed a check (missing values, backwards timestamps, zero duration): {int((raw.error.fillna('') != '').sum())}.",
          f"- Class label in the filename vs the `.info` file: {int((raw.exercise_class != raw.exercise_class_from_filename).sum())} disagreements. "
          f"Folder name vs `.info` nickname: {int((raw.info_nickname.str.lower() != raw.participant_id.str.lower()).sum())} disagreements.",
          "- Class 06 is spelled `DEADLIFT` in the `.info` files (the README has `DEAD_LIFT`).",
          "- Filenames are `<id>_<yyyy>_<mmdd>_<hhmmss>_segment<NN>_<class>.csv`. `NN` is the order within the session, not the class.",
          "", "## 2. Participants and sessions", "",
          f"- Sessions per participant: {dist(pp.sessions)}  (value: number of participants)",
          f"- Recording days per participant: {dist(pp.days)}",
          f"- Participants with >=2 sessions: {(pp.sessions >= 2).sum()}; >=3 sessions: {(pp.sessions >= 3).sum()}",
          f"- Participants with >=2 days: {(pp.days >= 2).sum()}; >=3 days: {(pp.days >= 3).sum()}",
          f"- Bouts per participant: median {pp.bouts.median():.0f} (range {pp.bouts.min()}-{pp.bouts.max()})",
          f"- Unique classes per participant: {dist(pp.classes)}",
          f"- Classes per session: {dist(per_sess_classes)}. **A session is one circuit of the 15 exercises, one set each.**",
          f"- Sessions on the same day are usually back-to-back (see `STATUS.md`), so **the split between calibration/training and test data is by day, not by session.**",
          f"- Lifting experience (months): median {pp.experience_months.median():.0f}, IQR {pp.experience_months.quantile(.25):.0f}-{pp.experience_months.quantile(.75):.0f}, "
          f"range {pp.experience_months.min():.0f}-{pp.experience_months.max():.0f}; {int((pp.experience_months == 0).sum())} participants report 0.",
          f"- Gender: {', '.join(f'{k} {v}' for k, v in pp.gender.value_counts().items())}.",
          "", "## 3. Classes", "",
          "| class | name | bouts | reps | participants | median bout (s) |", "|---|---|---|---|---|---|"]
    for r in pc.itertuples():
        L.append(f"| {r.exercise_class:02d} | {r.exercise_name} | {r.bouts} | {r.reps:,} | {r.participants} | {r.median_bout_s:.1f} |")
    L += ["", f"- Class imbalance (largest/smallest bouts): {pc.bouts.max() / pc.bouts.min():.2f}; "
          f"by reps: {pc.reps.max() / pc.reps.min():.2f}. Effectively balanced.",
          "", "## 4. Sampling rate", "",
          f"- Per bout, (samples-1)/duration: median {fs.median():.1f} Hz, IQR {fs.quantile(.25):.1f}-{fs.quantile(.75):.1f}, "
          f"1st-99th pct {fs.quantile(.01):.1f}-{fs.quantile(.99):.1f}, range {fs.min():.1f}-{fs.max():.1f}.",
          f"- Per participant median: {fs_pp.min():.1f}-{fs_pp.max():.1f} Hz.",
          f"- ~{m.frac_shared_timestamp.median():.0%} of rows share a timestamp with the previous row (BLE bursts). These are distinct samples and are kept; "
          "we assume even spacing within a bout and resample to 30 Hz (see `STATUS.md`).",
          "", "## 5. Feasibility of the team design", "",
          "Training uses **day 1** only; testing uses **later days** only.",
          "",
          f"- Participants with >=2 recording days: **{int(pp.eligible.sum())}**.",
          f"- Of those, participants with every class on day 1 and on a later day (needed for k = 1 set/exercise): **{n_elig}**.",
          f"- Of those, participants with >=2 day-1 sets of every class (needed for k = 2): **{n_k2}**.",
          f"- Day-1 sessions among the eligible: {dist(pp[pp.eligible].day1_sessions)}.",
          f"- Classes recurring across days, among the eligible: {dist(pp[pp.eligible].classes_recurring_across_days)}.",
          f"- Later-day test bouts per eligible participant: median {pp[pp.eligible].later_bouts.median():.0f} "
          f"(range {pp[pp.eligible].later_bouts.min()}-{pp[pp.eligible].later_bouts.max()}).",
          f"- Not eligible (only one recording day): {', '.join(pp[~pp.eligible].index)}.",
          "", "## 6. Recommended grid", "",
          f"- **Pool: the {n_k2} participants who support k = 2**, used for both k = 1 and k = 2 so the comparison is paired "
          f"(same teams, same test athletes). Dropped from the pool: "
          f"{', '.join(pp[pp.eligible_k1 & ~pp.eligible_k2].index)} (fewer than 2 day-1 sets of some exercise).",
          f"- Each repeat holds out {N_NEW} pool participants as never-recorded \"new athletes\"; the team is drawn from the remaining {max_team}.",
          f"- **Team size N: {', '.join(map(str, teams))}.**",
          "- **Sets per exercise per athlete, k: 1, 2** (day 1 holds two circuits). For k = 1, one of the two day-1 sets per exercise is chosen at random with a fixed seed.",
          "- Test sets: later-day bouts of the team (\"recorded\") and of the held-out athletes (\"new\"). Test bouts are never used for training.",
          "- Participants are the statistical unit: metrics are computed per test athlete, then summarized across athletes and repeats.",
          ]
    (ROOT / "DATA_AUDIT.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("\n".join(L))


if __name__ == "__main__":
    main()
